### ISSUE TITLE
Access Grants should support limited control scenarios

### ISSUE THREAD

**Issue by justinwb** [solid/data-interoperability-panel#100]
As currently written, access to the Access Grant Registry is reserved for Trusted Agent Access. However, in cases where a given agent is given control permissions on a subset of data (e.g. a Data Registration or instance(s) of a Data Registration), they should to be able to update the access grant registry with access changes they make. Without this support, we will end up with (more) frequent inconsistencies in the Access Grant Registry and the actual permissions granted to items in the Data Registry.

**Comment by elf-pavlik** [comment]
Recalling our conversation from last meeting it made me thinking about conversation I started in https://github.com/solid/authorization-panel/discussions/203

If we would use Data Grant as Credential / Capability, we wouldn't need to add that Data Grant 'out of band' since Resource Client could get it (or child capability) from Requesting Party and present it while making request. Possibly it could also use UMA-ish claim pushing to exchange it for a simpler token (also suggested in https://github.com/zenomt/webid-auth-protocol#webid-oidc-proof-of-possession-operation )

I believe this would also address https://solid.github.io/authorization-panel/authorization-ucr/#uc-client-constraints where User granting access to Application doesn't even have limited control.

**Comment by justinwb** [comment]
Noting that we've agreed not to support of this pattern altogether. Closing this issue.
