### ISSUE TITLE
AllInstances scope should still take into account referenced types

### ISSUE THREAD

**Issue by justinwb** [solid/data-interoperability-panel#118]
Use case: Access Need Group has a project as a primary (root) access need, and project has task as a referenced access need. User is presented a consent view like Figure 21 at https://solid.github.io/data-interoperability-panel/specification/#authz-workflows. Their expectation is that choosing all projects and tasks would only include tasks linked to projects, but the current operations would include all tasks, whether they are linked to projects or not.

**Comment by elf-pavlik** [comment]
During TS implementation call we discussed this case again. We agreed that:

1. Referenced Data Grant (e.g. Tasks) always needs to depend on the Data Grant referencing it (e.g. Projects)
1. We can use *InheritedInstances* on Referenced Data Grant (e.g. Tasks) even if Data Grant referencing it (e.g. Projects) uses *SelectedInstances*
1. We can remove *AllInstances* from Referenced Data Grant and only use it with regular *Data Grant*, otherwise we would go against the first point on this list.

**Comment by justinwb** [comment]
> 2\. We can use _InheritedInstances_ on Referenced Data Grant (e.g. Tasks) even if Data Grant referencing it (e.g. Projects) uses _SelectedInstances_

I think you mean _AllInstances_ in place of _SelectedInstances_ here?
