### ISSUE TITLE
Separate operations from main specification document

### ISSUE THREAD

**Issue by justinwb** [solid/data-interoperability-panel#148]
- [x] Create format / outline for new document
- [x] Move operations from specification document

*Note - Use https://www.w3.org/TR/json-ld-api/ for inspiration*

**Comment by kjetilk** [comment]
With "operations", do you mean the actual HTTP operations? 

In that case, my ambition is that you should simply be able to reference the Protocol for that. I made an issue about it: https://github.com/solid/specification/issues/260 Not sure when we'll get to that, but I feel it is quite urgent, since it would make other documents a lot slimmer by taking a burden off of them. You should never need to mention what should happen on the HTTP level, that should always be a reference to the Protocol.

**Comment by justinwb** [comment]
> With "operations", do you mean the actual HTTP operations?

@kjetilk No these are operations specific to functionality detailed in the application interoperability specification, such as [Access Grant Operations](https://solid.github.io/data-interoperability-panel/specification/#grants-operations).
