### ISSUE TITLE
Terminology: Access Consent

### ISSUE THREAD

**Issue by laurensdeb** [solid/data-interoperability-panel#242]
It might be a good idea to pause at the [Access Consent](https://solid.github.io/data-interoperability-panel/specification/#access-consent) terminology in the specification.

The way this is currently defined (and the word "consent") itself, may restrict a reader's interpretation of the concept. Firstly, because "consent" is quite a loaded term from a business and legal perspective (cfr. [informed or explicit consent](https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/consent/what-is-valid-consent/)). Secondly because the decision to share some resources may only indirectly flow from the actions of a social agent, e.g. because they have entered into some contract (which was for example presented to the authorization agent as a VC), because they have assigned a proxy to manage access for them, ...

## Suggested course of action
- Specify how broadly we should interpret the idea an ["Access Consent"](https://solid.github.io/data-interoperability-panel/specification/#access-consent) aims to materialize and how we can clarify this in the specification.
- Replace the term "consent" with something more general, like Access Clearance or Access Approval.

**Comment by tomhgmns** [comment]
Thanks for the suggestion. I think replacing the term with another term might be the best idea moving forward.

**Comment by elf-pavlik** [comment]
I think we picked it mostly because it gets created after the user's interaction with the consent screen.

👍 changing terminology, I was thinking about *Access Policy* since they are higher level than *Access Grants*. I wouldn't worry about naming collision with ACP, this term is pretty common and can be used in different specs to mean something different.

**Comment by justinwb** [comment]
> It might be a good idea to pause at the [Access Consent](https://solid.github.io/data-interoperability-panel/specification/#access-consent) terminology in the specification.

Agree with the points made by @laurensdeb, and have no strong objection to changing the terminology. I do believe that we provide a lot of elements that can be used in (for example) a consent decision with legal basis, but there are certainly scenarios and elements where additional information may need to be presented or recorded in conjunction with what we're doing now. Ideally we can align efforts so that we can combine things together when legal consent needs to be incorporated.

> * Replace the term "consent" with something more general, like Access Clearance or Access Approval.

Lets use this thread to catalog a list of name choices and see if we can make a determination in next week's panel session (also adding a few more into the mix).

- Access Clearance 
- Access Approval 
- Access Policy 
- Access Decision 
- Access Authorization 
- Access Choice
- Access Selection

**Comment by justinwb** [comment]
In the panel meeting of 2/23 - there [was a decision](https://github.com/solid/data-interoperability-panel/blob/main/meetings/2022-02-23.md#terminology---access-consent) to rename access consents in response to [this GitHub issue](https://github.com/solid/data-interoperability-panel/issues/242). Just created a poll for panel members to weigh in on the options they like most!

https://pollunit.com/en/polls/osk8gjzizehvo-vqkbobda

**Comment by timbl** [comment]
No one has suggested "permissions" so I will throw that in, as people might feel it is less loaded.

**Comment by justinwb** [comment]
> No one has suggested "permissions" so I will throw that in, as people might feel it is less loaded.

Good call @timbl - added to the poll!

**Comment by elf-pavlik** [comment]
This was addressed in #255
