### ISSUE TITLE
Social Feeds / Profiles - this panel or separate?

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/data-interoperability-panel#4]
Question for the panel.
Would it make sense to have a separate Social Feeds panel (to recommend / standardize things like how to model social media operations like following / followed by, ActivityStreams 2 feeds, interop with ActivityPub and/or RSS, etc)?
Similarly, we're currently informally using the WebID Profile for userinfo / social profile (in addition for using it for authentication and settings/preferences). It would be great to separate those concerns, and standardize the social profile aspect of it.

Do we want to handle it here in the Data Interop panel, or in a separate panel?

**Comment by RubenVerborgh** [comment]
Below is my personal opinion.

There are two things we need to do within Solid:

1. **data model alignment** such that, in the short term, apps interoperate because they use the exact same vocabularies / data shapes. I consider these _guidance_, not mandatory. They have a placeholder here: https://solid.github.io/specification/#client-guidance

2. **data model alignment mechanisms** such that, in the long term, pods can use whatever vocabularies / data shapes they want, but apps will still interoperate. I consider these mandatory (when ready). They have a placeholder here: https://solid.github.io/specification/#shapes-footprints

Also see https://github.com/solid/data-interoperability-panel/issues/2#issuecomment-519393618 for the distinction.

---

To now more directly answer your question, concrete data models belong in 1. It is something we could/should investigate in this panel.

**Comment by dmitrizagidulin** [comment]
@RubenVerborgh - I completely agree; those two items are a really important distinction.

So as far as item 1, data model alignment, where should that guidance discussion take place? a) here in this panel, b) a separate Social Feeds panel, or even c) External Outreach / Interop (the parts about interoperating with ActivityPub etc)?

**Comment by RubenVerborgh** [comment]
_a)_ for me; but there might be two parallel streams in this panel then.

**Comment by dmitrizagidulin** [comment]
Ok, going with "let's standardize social feed / profile stuff in this panel", then.
(Closing this issue, question answered.)
