### ISSUE TITLE
Remove hard requirements on UUIDs

### ISSUE THREAD

**Issue by kjetilk** [solid/data-interoperability-panel#99]
There are a few places, like § 5.3 Resource Hierarchy, where the App Interop specs sets requirements on the resource names. I tend to view the server as sovereign on resource names, and that in only very rare cases (e.g. `.well-known`) should specs define resource names. For other cases, there should be a discovery mechanism (possibly grounded in `.well-known`). In particular, it requires the use of UUIDs for resource names. I don't see a justification for this choice, so, why did you do that?

**Comment by ericprud** [comment]
I can speak a bit to the intent. The idea is that there be no reliance on the name, much as you as a user have no idea how the storage in your phone is organized (well, **you** might, but...). I don't know of a reason to prescribe UUIDs above, say, sequential Fibonacci numbers.

**Comment by kjetilk** [comment]
Yeah, I see that most implementations may want that, but that should be up to them, not the spec, I would say... I would leave it as an implementation detail.

**Comment by justinwb** [comment]
This is a valid point @kjetilk. Our rationale was primarily that we didn't want people to have to pick names themselves, didn't want to have different applications collide on update if they used the same resource naming scheme, and wanted to protect against leakage through the resource name. UUIDs were/are a good way to avoid all of that, but you're right that it's probably a bit heavy handed for a spec to prescribe them, instead of saying that they must/should honor the requirements.

We discussed this issue [today in the panel session](https://github.com/solid/data-interoperability-panel/blob/master/meetings/2021-05-04.md#99---why-requirements-on-resource-names). There was broad agreement in removing the hard requirement on UUIDs and replacing with requirements that could be fulfilled with different schemes. 

We have an action item now to update the spec to reflect this. This issue will be left open until the PR is merged to resolve.

**Comment by kjetilk** [comment]
Indeed, I think that is an important mechanism. We might even mention it in the protocol spec.
